export const QR_KEY = {
    COURSE: "COURSE",
    COURSE_DETAIL: "COURSE_DETAIL",
    OBJECT_USER: "OBJECT_USER",
    KNOW: "KNOW",
    BLOG: "BLOG",
    BLOG_DETAIL: "BLOG_DETAIL",
    COURSE_ORDER: "COURSE_ORDER",
    PUT_PROFILE: "PUT_PROFILE",
};
